version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_NAME: registration_db
      DB_USER: registration_user
      DB_PASS: registration_password

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "8086:80"
    environment:
      MYSQL_ROOT_PASSWORD: registration_password
      MYSQL_DATABASE: registration_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: